// package/zerobias/example-nextjs-v2/src/app/products/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import Image from "next/image";
import type { ProductExtended } from "@zerobias-com/portal-sdk";
import { useSession } from "@/context/session-context";
import { toUserMessage } from "@/lib/errors";
import {
  RemoteTable,
  type Column,
  type ColumnOptionsMap,
  type FilterState,
  type SortState,
} from "@/components/RemoteTable";

const PAGE_SIZE = 10;

/**
 * Columns are declarative and static — which of them SORT or FILTER is decided at runtime
 * by the server's `searchProductsOptions()` metadata, not here. Nothing below says
 * `sortable: true`.
 */
const COLUMNS: Column<ProductExtended>[] = [
  {
    key: "imageUrl",
    header: "Logo",
    width: "56px",
    cell: (p) =>
      p.imageUrl ? (
        <Image src={p.imageUrl.toString()} alt={p.name} width={32} height={32} />
      ) : null,
  },
  { key: "name", header: "Name", cell: (p) => p.name },
  { key: "code", header: "Code", cell: (p) => <code>{p.code}</code> },
  {
    key: "description",
    header: "Description",
    cell: (p) => p.description ?? "—",
  },
  {
    key: "status",
    header: "Status",
    // The options endpoint calls this column `status`; SearchProductBody wants `statuses`.
    // Without this mapping the filter is silently ignored server-side. See RemoteTable.
    filterParam: "statuses",
    cell: (p) => (
      <span
        className={`chip ${p.status?.toString() === "published" ? "success" : "neutral"}`}
      >
        {p.status?.toString()}
      </span>
    ),
  },
];

/**
 * Products Catalog — the canonical "remote table" pattern.
 *
 * Two calls work together, and this pairing is the thing to copy:
 *
 *   portalClient.getProductApi().searchProductsOptions()
 *     -> per-column metadata: which columns are sortable / searchable / filterable,
 *        and for filterable ones, the allowed values.
 *
 *   portalClient.getProductApi().search(body, page, size, sort)
 *     -> PagedResults<ProductExtended>; `.items` holds the rows.
 *
 * The UI is DRIVEN by the options call. We never hardcode "status is filterable" or
 * "name is sortable" — the server says so, and `RemoteTable` renders accordingly. Add a
 * filter server-side and it appears here with no client release; remove one and it
 * disappears. Every searchable platform endpoint has this same `*Options` sibling
 * (`searchTasksOptions()`, `taskSearchOptions(boardId)`, ...), so this pattern ports
 * directly to tasks, boards, findings, evidence — anything with a search endpoint.
 *
 * Paging is prev/next rather than a numbered pager: search returns no total count, so
 * there is no last page to compute.
 */
export default function ProductsPage() {
  const { api, org } = useSession();

  const [products, setProducts] = useState<ProductExtended[]>([]);
  const [options, setOptions] = useState<ColumnOptionsMap | undefined>();
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState<SortState | null>(null);
  const [filters, setFilters] = useState<FilterState>({});
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // 1. Column metadata. Fetched once — it describes the endpoint, not the result set.
  useEffect(() => {
    if (!api) return;
    api.portalClient
      .getProductApi()
      .searchProductsOptions()
      .then((res) => {
        // The wrapper is `{ options: { [columnName]: ResultsColumnOptions } }`.
        setOptions(res.options as unknown as ColumnOptionsMap);
      })
      .catch((err) => {
        // Non-fatal: without options the table still lists rows, just without
        // server-driven sort/filter affordances.
        console.warn("searchProductsOptions failed; table falls back to plain list", err);
      });
  }, [api]);

  // 2. The rows. Re-runs whenever sort/filter/search/page/org changes.
  //
  // NOTE: this does NOT flip `loading` on. Setting state synchronously inside an effect
  // cascades renders (react-hooks/set-state-in-effect). The user actions below own the
  // spinner instead: they set `loading` as they change the query, and the fetch clears it.
  const load = useCallback(() => {
    if (!api) return;

    // Filter keys come from the options metadata, so the body is assembled from whatever
    // the server declared filterable — not from a hardcoded list.
    //
    // The one thing that does NOT come for free: the options endpoint is keyed by COLUMN
    // name, but the search body's field may be named differently. Products declares the
    // column `status`, while SearchProductBody takes `statuses` (a plural array). Sending
    // `status` gets silently ignored and you get unfiltered rows back — a filter that
    // "does nothing" and looks like a UI bug. `Column.filterParam` carries that mapping.
    const body: Record<string, unknown> = {};
    if (search.trim()) body.search = search.trim();
    for (const [key, values] of Object.entries(filters)) {
      if (!values.length) continue;
      const param = COLUMNS.find((c) => c.key === key)?.filterParam ?? key;
      body[param] = values;
    }

    return api.portalClient
      .getProductApi()
      .search(
        body as never,
        page,
        PAGE_SIZE,
        sort ? ({ active: sort.active, direction: sort.direction } as never) : undefined,
      )
      .then((results) => {
        setProducts(results.items);
        setError(null);
      })
      .catch((err) => {
        console.error("Products search failed", err);
        setError(toUserMessage(err));
        setProducts([]);
      })
      .finally(() => setLoading(false));
  }, [api, page, sort, filters, search]);

  useEffect(() => {
    void load();
  }, [load, org?.id]);

  // Any change to the query resets to page 1 — otherwise you land on an empty page 4 —
  // and shows the loading state. These handlers, not the effect, own `loading`.
  const changeQuery =
    <T,>(setter: (v: T) => void) =>
    (value: T) => {
      setLoading(true);
      setPage(1);
      setter(value);
    };

  const changePage = (next: number) => {
    setLoading(true);
    setPage(next);
  };

  return (
    <div>
      <h1>Products Catalog</h1>
      <p className="subtitle">
        <code>getProductApi().searchProductsOptions()</code> drives the table;{" "}
        <code>.search(body, page, size, sort)</code> fills it.
      </p>

      <RemoteTable
        columns={COLUMNS}
        rows={products}
        rowKey={(p) => p.id.toString()}
        loading={loading}
        error={error}
        emptyMessage="No products found."
        columnOptions={options}
        sort={sort}
        onSortChange={changeQuery(setSort)}
        filters={filters}
        onFiltersChange={changeQuery(setFilters)}
        search={search}
        onSearchChange={changeQuery(setSearch)}
        searchPlaceholder="Search products…"
        page={page}
        pageSize={PAGE_SIZE}
        hasNext={products.length === PAGE_SIZE}
        onPageChange={changePage}
      />
    </div>
  );
}

// package/zerobias/example-angular-v2/src/app/pages/products/products.ts
import { Component, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MatTableModule } from '@angular/material/table';
import {
  ZB_TABLE_MODE,
  ZbRemoteTableComponent,
  ZbRemoteTableContainerComponent,
  ZbRemoteTableHeaderComponent,
  ZbRemoteTableService,
  ZbResourceStatusComponent,
  type ZbRemoteTableConfig,
} from '@zerobias-org/ngx-library';
import { SearchProductBody } from '@zerobias-com/portal-sdk';

import { SessionService } from '../../core/session.service';
import type { RemoteTableColumnOptions } from '../../shared/remote-table-column-options';

/**
 * Products Catalog — the canonical `zb-remote-table` read demo, the Angular counterpart of the
 * React app's Products page. Two portal calls work together:
 *
 *   portalClient.getProductApi().searchProductsOptions()
 *     -> per-column metadata (which columns are sortable / filterable + allowed values). Passed to
 *        the table via `setData({ getColumnOptions })`; `zb-remote-table-header` renders the sort /
 *        filter affordances the SERVER declares — nothing here hardcodes "status is filterable".
 *
 *   portalClient.getProductApi().search(body, pageNumber, pageSize, sort)
 *     -> PagedResults<ProductExtended>; `.items` are the rows.
 *
 * Mechanics come from ngx-library: extend `ZbRemoteTableContainerComponent`, provide
 * `ZbRemoteTableService` per-component. In COMPONENT mode the base calls `list()` on init and again
 * on every sort/filter/search/page change; we only implement `list()`: read `getRequestParams()`,
 * call the SDK, hand the result to `setData()`.
 *
 * Note the one non-obvious mapping: the options endpoint keys the column `status`, but
 * `SearchProductBody` wants `statuses` (a plural array) — `filterParams`/`arrayParams` below carry
 * that so the filter isn't silently dropped server-side.
 */
@Component({
  selector: 'app-products',
  imports: [
    MatTableModule,
    ZbRemoteTableComponent,
    ZbRemoteTableHeaderComponent,
    ZbResourceStatusComponent,
  ],
  providers: [ZbRemoteTableService],
  template: `
    <section class="intro">
      <h1>Products Catalog</h1>
      <p class="lead">
        <code>getProductApi().searchProductsOptions()</code> drives the columns;
        <code>.search(body, page, size, sort)</code> fills them.
      </p>
    </section>

    <div class="table-container">
    <zb-remote-table
      [columns]="displayColumns"
      [columnLabels]="displayColumnLabels"
      [loading]="loading"
      [selectableRows]="false"
      [rowClickEnabled]="false"
      searchPageKey="search"
    >
      <ng-container matColumnDef="imageUrl">
        <th mat-header-cell *matHeaderCellDef class="logo-col">{{ displayColumnLabels['imageUrl'] }}</th>
        <td mat-cell *matCellDef="let p">
          @if (p.imageUrl) {
            <img class="zb-ui-resource-image s20" [src]="p.imageUrl.toString()" [alt]="p.name" />
          }
        </td>
      </ng-container>

      <ng-container matColumnDef="name">
        <th mat-header-cell *matHeaderCellDef>
          <zb-remote-table-header columnKey="name">
            <span>{{ displayColumnLabels['name'] }}</span>
          </zb-remote-table-header>
        </th>
        <td mat-cell *matCellDef="let p">{{ p.name }}</td>
      </ng-container>

      <ng-container matColumnDef="code">
        <th mat-header-cell *matHeaderCellDef>{{ displayColumnLabels['code'] }}</th>
        <td mat-cell *matCellDef="let p"><code>{{ p.code }}</code></td>
      </ng-container>

      <ng-container matColumnDef="description">
        <th mat-header-cell *matHeaderCellDef>{{ displayColumnLabels['description'] }}</th>
        <td mat-cell *matCellDef="let p">{{ p.description ?? '—' }}</td>
      </ng-container>

      <ng-container matColumnDef="status">
        <th mat-header-cell *matHeaderCellDef>
          <zb-remote-table-header columnKey="status">
            <span>{{ displayColumnLabels['status'] }}</span>
          </zb-remote-table-header>
        </th>
        <td mat-cell *matCellDef="let p">
          <zb-resource-status [label]="p.status" [pill]="true"></zb-resource-status>
        </td>
      </ng-container>
    </zb-remote-table>
    </div>
  `,
  styles: `
    /* Fill the shell's content height and let the table flex into the remaining space.
       zb-remote-table is :host{height:100%} + an inner .zb-remote-table-table-container
       {flex:1;overflow:auto} that owns infinite scroll ([scrollWindow]=false). That inner
       container only scrolls if it gets a BOUNDED height — i.e. this host must be bounded and
       the table must flex, not grow with content. Without this the whole page scrolls instead,
       the scroll event never reaches the table, and infinite scroll never loads page 2. */
    :host { display: block; }
    /* The table lives in its own fixed-height box (NOT tied to the shell height), so only its
       inner scroll container overflows — no second page scrollbar. Don't set display/height on
       zb-remote-table: it already styles itself display:flex; height:100% (ViewEncapsulation.None),
       and its 100% resolves against this 600px box. Overriding display:block collapses its internal
       flex column and kills the scroll. */
    .table-container { height: 600px; }
    .intro h1 { margin: 0 0 var(--zb-spacing-xs); }
    .lead { color: var(--zb-secondary-text); margin: 0 0 var(--zb-spacing-md); }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--zb-primary); }
    .logo-col { width: 56px; }
  `,
})
export class Products extends ZbRemoteTableContainerComponent {
  private readonly session = inject(SessionService);

  // COMPONENT mode: the base drives list() on init + on every table interaction (no URL sync).
  override mode = ZB_TABLE_MODE.COMPONENT;

  override config: ZbRemoteTableConfig = {
    // Large page so the first load overflows the bounded scroll container and shows a scrollbar —
    // that's what lets infinite scroll fire (onScrollDown) to fetch the next page. The endpoint
    // returns no total count, so there's no numbered paginator; paging is scroll-driven.
    pageSize: 50,
    searchParams: ['search'],
    // The `status` column filters into the body's `statuses` array (see class doc).
    filterParams: ['statuses'],
    arrayParams: ['statuses'],
  };

  override displayColumns = ['imageUrl', 'name', 'code', 'description', 'status'];
  override displayColumnLabels: Record<string, string> = {
    imageUrl: 'Logo',
    name: 'Name',
    code: 'Code',
    description: 'Description',
    status: 'Status',
  };

  // The base requires these three via super() — they can't move to inject() (super() needs them
  // before field initializers run). Everything else (session) is injected.
  constructor(activatedRoute: ActivatedRoute, router: Router, tableService: ZbRemoteTableService) {
    super(activatedRoute, router, tableService);
  }

  override list(): void {
    const api = this.session.api();
    if (!api) return;

    const params = this.tableService.getRequestParams();
    const body: SearchProductBody = {};
    if (params['search']) body.search = params['search'];
    if (params['statuses']) body.statuses = params['statuses'];

    this.loading = true;
    const productApi = api.portalClient.getProductApi();
    productApi
      .search(body, params['pageNumber'], params['pageSize'], params['sort'])
      .then((results) => {
        this.tableService.setData({
          items: results.items,
          count: results.count ?? results.items.length,
          // Server-declared sort/filter metadata — fetched lazily, only when the table asks.
          getColumnOptions: () =>
            productApi
              .searchProductsOptions()
              .then((w) => w.options as unknown as Record<string, RemoteTableColumnOptions>),
        });
      })
      .catch((err) => {
        console.error('Products search failed', err);
        this.tableService.setData({ items: [], count: 0 });
      })
      .finally(() => {
        this.loading = false;
      });
  }
}
