// package/zerobias/example-angular-v2/src/app/pages/projects/projects.ts
import { Component, inject, signal } from '@angular/core';
import { NgClass } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { MatTableModule } from '@angular/material/table';
import {
  ZB_TABLE_MODE,
  ZbRemoteTableComponent,
  ZbRemoteTableContainerComponent,
  ZbRemoteTableHeaderComponent,
  ZbRemoteTableService,
  ZbResourceStatusComponent,
  type ZbRemoteTableConfig,
} from '@zerobias-org/ngx-library';
import { SearchProjectBody, type ProjectExtended } from '@zerobias-com/portal-sdk';

import { SessionService } from '../../core/session.service';
import { Drawer } from '../../shared/drawer/drawer';
import type { RemoteTableColumnOptions } from '../../shared/remote-table-column-options';
import { CreateProjectForm } from './create-project-form';

/**
 * Projects — the second `zb-remote-table` read demo (twin of the React app's Projects
 * page). Same two-call shape as Products:
 *
 *   portalClient.getProjectApi().searchOptions()               -> per-column sort/filter metadata
 *   portalClient.getProjectApi().search(body, page, size, sort) -> PagedResults<ProjectExtended>
 *
 * A project sits at the top of the containment chain: project -> boards -> activities -> tasks.
 *
 * Shape trap (same as Products): the options endpoint keys columns `status` / `visibility`, but
 * `SearchProjectBody` wants the PLURAL arrays `statuses` / `visibilities`. `filterParams` /
 * `arrayParams` below carry that mapping so the filters aren't silently dropped server-side.
 */
@Component({
  selector: 'app-projects',
  imports: [
    NgClass,
    MatTableModule,
    ZbRemoteTableComponent,
    ZbRemoteTableHeaderComponent,
    ZbResourceStatusComponent,
    Drawer,
    CreateProjectForm,
  ],
  providers: [ZbRemoteTableService],
  template: `
    <section class="intro">
      <div class="intro-head">
        <h1>Projects</h1>
        <button type="button" class="btn-stroked" (click)="createOpen.set(true)">+ Create Project</button>
      </div>
      <p class="lead">
        <code>getProjectApi().searchOptions()</code> drives the columns;
        <code>.search(body, page, size, sort)</code> fills them. A project contains boards, which
        carry the activities tasks hang off. Click a row to drill into its detail.
      </p>
    </section>

    <app-drawer [open]="createOpen()" heading="Create project" (close)="createOpen.set(false)">
      @if (createOpen()) {
        <app-create-project-form />
      }
    </app-drawer>

    <div class="table-container">
    <zb-remote-table
      [columns]="displayColumns"
      [columnLabels]="displayColumnLabels"
      [loading]="loading"
      [selectableRows]="false"
      [rowClickEnabled]="true"
      (rowClick)="openDetail($event)"
      searchPageKey="search"
    >
      <ng-container matColumnDef="name">
        <th mat-header-cell *matHeaderCellDef>
          <zb-remote-table-header columnKey="name">
            <span>{{ displayColumnLabels['name'] }}</span>
          </zb-remote-table-header>
        </th>
        <td mat-cell *matCellDef="let p">{{ p.name }}</td>
      </ng-container>

      <ng-container matColumnDef="type">
        <th mat-header-cell *matHeaderCellDef>{{ displayColumnLabels['type'] }}</th>
        <td mat-cell *matCellDef="let p">
          <span class="zb-chip square generic">{{ p.projectType?.name ?? p.type }}</span>
        </td>
      </ng-container>

      <ng-container matColumnDef="status">
        <th mat-header-cell *matHeaderCellDef>
          <zb-remote-table-header columnKey="status">
            <span>{{ displayColumnLabels['status'] }}</span>
          </zb-remote-table-header>
        </th>
        <td mat-cell *matCellDef="let p">
          <zb-resource-status [label]="p.status" [pill]="true"></zb-resource-status>
        </td>
      </ng-container>

      <ng-container matColumnDef="visibility">
        <th mat-header-cell *matHeaderCellDef>
          <zb-remote-table-header columnKey="visibility">
            <span>{{ displayColumnLabels['visibility'] }}</span>
          </zb-remote-table-header>
        </th>
        <td mat-cell *matCellDef="let p">
          <span class="zb-chip square visibility" [ngClass]="p.visibility?.toString()?.toLowerCase()">
            {{ p.visibility }}
          </span>
        </td>
      </ng-container>

      <ng-container matColumnDef="boardCount">
        <th mat-header-cell *matHeaderCellDef class="num">{{ displayColumnLabels['boardCount'] }}</th>
        <td mat-cell *matCellDef="let p" class="num">{{ p.boardCount ?? 0 }}</td>
      </ng-container>

      <ng-container matColumnDef="memberCount">
        <th mat-header-cell *matHeaderCellDef class="num">{{ displayColumnLabels['memberCount'] }}</th>
        <td mat-cell *matCellDef="let p" class="num">{{ p.memberCount ?? 0 }}</td>
      </ng-container>
    </zb-remote-table>
    </div>
  `,
  styles: `
    :host { display: block; }
    .intro-head { display: flex; align-items: center; justify-content: space-between; gap: var(--zb-spacing-md); }
    .intro h1 { margin: 0 0 var(--zb-spacing-xs); }
    .lead { color: var(--zb-secondary-text); margin: 0 0 var(--zb-spacing-md); }
    .btn-stroked {
      height: 38px;
      padding: 0 var(--zb-spacing-md);
      border: 1px solid var(--zb-primary);
      border-radius: 6px;
      background: transparent;
      color: var(--zb-primary);
      font-size: var(--zb-font-size-md);
      cursor: pointer;
      white-space: nowrap;
    }
    .btn-stroked:hover { background: var(--zb-table-row-hover); }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--zb-primary); }
    /* Fixed-height box so only the table's inner container scrolls (see products.ts for the why). */
    .table-container { height: 600px; }
    .num { text-align: right; }
  `,
})
export class Projects extends ZbRemoteTableContainerComponent {
  private readonly session = inject(SessionService);

  /** Create-project drawer (code-reveal write demo). */
  protected readonly createOpen = signal(false);

  /** Drill into a project's detail (routed page — query param for static-export compatibility).
   *  `this.router` is the base class's protected Router — no second injection needed. */
  protected openDetail(project: ProjectExtended): void {
    this.router.navigate(['/projects/detail'], { queryParams: { id: project.id.toString() } });
  }

  // COMPONENT mode: the base drives list() on init + on every table interaction (no URL sync).
  override mode = ZB_TABLE_MODE.COMPONENT;

  override config: ZbRemoteTableConfig = {
    // Large page so the first load overflows the bounded scroll container; paging is scroll-driven
    // (the endpoint returns no total count, so there's no numbered paginator).
    pageSize: 50,
    searchParams: ['search'],
    // status -> statuses, visibility -> visibilities (see class doc).
    filterParams: ['statuses', 'visibilities'],
    arrayParams: ['statuses', 'visibilities'],
  };

  override displayColumns = ['name', 'type', 'status', 'visibility', 'boardCount', 'memberCount'];
  override displayColumnLabels: Record<string, string> = {
    name: 'Name',
    type: 'Type',
    status: 'Status',
    visibility: 'Visibility',
    boardCount: 'Boards',
    memberCount: 'Members',
  };

  // The base requires these three via super() — they can't move to inject(). session is injected above.
  constructor(activatedRoute: ActivatedRoute, router: Router, tableService: ZbRemoteTableService) {
    super(activatedRoute, router, tableService);
  }

  override list(): void {
    const api = this.session.api();
    if (!api) return;

    const params = this.tableService.getRequestParams();
    const body: SearchProjectBody = {};
    if (params['search']) body.search = params['search'];
    if (params['statuses']) body.statuses = params['statuses'];
    if (params['visibilities']) body.visibilities = params['visibilities'];

    this.loading = true;
    const projectApi = api.portalClient.getProjectApi();
    projectApi
      .search(body, params['pageNumber'], params['pageSize'], params['sort'])
      .then((results) => {
        this.tableService.setData({
          items: results.items,
          count: results.count ?? results.items.length,
          // Server-declared sort/filter metadata — fetched lazily, only when the table asks.
          getColumnOptions: () =>
            projectApi
              .searchOptions()
              .then((w) => w.options as unknown as Record<string, RemoteTableColumnOptions>),
        });
      })
      .catch((err) => {
        console.error('Project search failed', err);
        this.tableService.setData({ items: [], count: 0 });
      })
      .finally(() => {
        this.loading = false;
      });
  }
}

// package/zerobias/example-nextjs-v2/src/app/projects/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { ProjectExtended } from "@zerobias-com/portal-sdk";
import { useSession } from "@/context/session-context";
import { toUserMessage } from "@/lib/errors";
import {
  RemoteTable,
  type Column,
  type ColumnOptionsMap,
  type FilterState,
  type SortState,
} from "@/components/RemoteTable";
import { CreateProjectDrawer } from "@/components/CreateProjectDrawer";

const PAGE_SIZE = 10;

/**
 * Projects — the top of the containment chain, and the THIRD consumer of RemoteTable
 * (after Products and Tasks). Same server-driven two-call pattern:
 *
 *   portalClient.getProjectApi().searchOptions()               -> per-column sort/filter metadata
 *   portalClient.getProjectApi().search(body, page, size, sort) -> PagedResults<ProjectExtended>
 *
 * A project contains boards; boards carry activities; tasks hang off activities. The detail view
 * drills that chain down to the project's own tasks. Reads live on `portalClient`; writes (create
 * project / manage members) live on `platformClient` — that split is consistent across the surface.
 *
 * Same shape trap as Tasks: the options endpoint keys columns as `status` / `visibility`, but
 * SearchProjectBody wants the PLURAL arrays `statuses` / `visibilities`. `Column.filterParam`
 * carries that mapping.
 */

const COLUMNS: Column<ProjectExtended>[] = [
  { key: "name", header: "Name", cell: (p) => p.name },
  {
    key: "projectType",
    header: "Type",
    cell: (p) => p.projectType?.name ?? p.type,
  },
  {
    key: "status",
    header: "Status",
    filterParam: "statuses", // options say `status`; SearchProjectBody wants `statuses`
    cell: (p) => <span className="chip neutral">{String(p.status)}</span>,
  },
  {
    key: "visibility",
    header: "Visibility",
    filterParam: "visibilities", // options say `visibility`; body wants `visibilities`
    cell: (p) => String(p.visibility),
  },
  {
    key: "boardCount",
    header: "Boards",
    align: "right",
    cell: (p) => p.boardCount ?? 0,
  },
  {
    key: "memberCount",
    header: "Members",
    align: "right",
    cell: (p) => p.memberCount ?? 0,
  },
];

export default function ProjectsPage() {
  const { api, org } = useSession();
  const router = useRouter();

  const [projects, setProjects] = useState<ProjectExtended[]>([]);
  const [options, setOptions] = useState<ColumnOptionsMap | undefined>();
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState<SortState | null>(null);
  const [filters, setFilters] = useState<FilterState>({});
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);

  // 1. Column metadata — describes the endpoint, fetched once.
  useEffect(() => {
    if (!api) return;
    api.portalClient
      .getProjectApi()
      .searchOptions()
      .then((res) => setOptions(res.options as unknown as ColumnOptionsMap))
      .catch((err) => {
        console.warn("Project searchOptions failed; table falls back to plain list", err);
      });
  }, [api]);

  // 2. The rows.
  const load = useCallback(() => {
    if (!api) return;

    const body: Record<string, unknown> = {};
    if (search.trim()) body.search = search.trim();
    for (const [key, values] of Object.entries(filters)) {
      if (!values.length) continue;
      const param = COLUMNS.find((c) => c.key === key)?.filterParam ?? key;
      body[param] = values;
    }

    return api.portalClient
      .getProjectApi()
      .search(
        body as never,
        page,
        PAGE_SIZE,
        sort ? ({ active: sort.active, direction: sort.direction } as never) : undefined,
      )
      .then((results) => {
        setProjects(results.items);
        setError(null);
      })
      .catch((err) => {
        console.error("Project search failed", err);
        setError(toUserMessage(err));
        setProjects([]);
      })
      .finally(() => setLoading(false));
  }, [api, page, sort, filters, search]);

  useEffect(() => {
    void load();
  }, [load, org?.id]);

  // Query changes reset to page 1 and own the loading state (not the effect).
  const changeQuery =
    <T,>(setter: (v: T) => void) =>
    (value: T) => {
      setLoading(true);
      setPage(1);
      setter(value);
    };

  const changePage = (next: number) => {
    setLoading(true);
    setPage(next);
  };

  return (
    <div>
      <div className="page-header">
        <h1>Projects</h1>
        <button type="button" className="btn-stroked" onClick={() => setCreateOpen(true)}>
          + Create Project
        </button>
      </div>
      <p className="subtitle">
        <code>getProjectApi().searchOptions()</code> drives the table;{" "}
        <code>.search(body, page, size, sort)</code> fills it. A project contains boards, which
        carry the activities tasks hang off.
      </p>

      <CreateProjectDrawer open={createOpen} onClose={() => setCreateOpen(false)} />

      <RemoteTable
        columns={COLUMNS}
        rows={projects}
        rowKey={(p) => p.id.toString()}
        onRowClick={(p) => router.push(`/projects/detail?id=${p.id}`)}
        loading={loading}
        error={error}
        emptyMessage="No projects found."
        columnOptions={options}
        sort={sort}
        onSortChange={changeQuery(setSort)}
        filters={filters}
        onFiltersChange={changeQuery(setFilters)}
        search={search}
        onSearchChange={changeQuery(setSearch)}
        searchPlaceholder="Search projects…"
        page={page}
        pageSize={PAGE_SIZE}
        hasNext={projects.length === PAGE_SIZE}
        onPageChange={changePage}
      />
    </div>
  );
}
