// package/zerobias/example-angular-v2/src/app/pages/projects/project-detail.ts
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { NgClass } from '@angular/common';
import { RouterLink } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import {
  ZbResourceStatusComponent,
  ZbSnakeToSpacesPipe,
} from '@zerobias-org/ngx-library';
import { SearchTaskBody } from '@zerobias-com/portal-sdk';

import { detailResource } from '../../shared/detail-resource';
import { Drawer } from '../../shared/drawer/drawer';
import { MarkdownViewer } from '../../shared/markdown-viewer/markdown-viewer';
import { CreateProjectForm } from './create-project-form';
import { EditProjectForm } from './edit-project-form';
import { ProjectTreeNodeComponent, type CreateParent } from './project-tree-node';

const TASK_PREVIEW = 10;

/**
 * ProjectDetail — the read drill-down for a project (twin of example-nextjs-v2's ProjectDetail).
 * Reached from the projects list via `/projects/detail?id=<uuid>` (query param, not a path param,
 * so it survives a static export). All reads are on `portalClient`:
 *
 *   getProjectApi().get(id)                    -> the project
 *   getProjectApi().listMembers(id)            -> members + roles
 *   getProjectApi().searchTasks(id, {}, 1, 10) -> a task preview
 *   getProjectApi().getTree(id, true)          -> the sub-project hierarchy
 *
 * The Edit button opens the code-reveal edit drawer.
 */
@Component({
  selector: 'app-project-detail',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    NgClass,
    RouterLink,
    MatIconModule,
    ZbResourceStatusComponent,
    ZbSnakeToSpacesPipe,
    Drawer,
    MarkdownViewer,
    CreateProjectForm,
    EditProjectForm,
    ProjectTreeNodeComponent,
  ],
  template: `
    <a class="back" routerLink="/projects"><mat-icon>arrow_back</mat-icon> Projects</a>

    @if (loading()) {
      <p class="state">Loading project…</p>
    } @else if (error()) {
      <p class="state error">{{ error() }}</p>
    } @else if (project(); as p) {
      <header class="head">
        <div class="title">
          <code class="code">{{ p.code ?? '—' }}</code>
          <h1>{{ p.name }}</h1>
          <zb-resource-status [label]="p.status" [pill]="true"></zb-resource-status>
        </div>
        <button type="button" class="btn-stroked" (click)="editOpen.set(true)">Edit</button>
      </header>

      @if (p.description) {
        <div class="desc"><app-markdown-viewer [content]="p.description" /></div>
      }

      <dl class="meta">
        <div><dt>Type</dt><dd>{{ p.projectType.name }}</dd></div>
        <div><dt>Visibility</dt><dd><span class="zb-chip square visibility" [ngClass]="p.visibility.toString().toLowerCase()">{{ p.visibility }}</span></dd></div>
        <div><dt>Owner</dt><dd>{{ p.owner.name }}</dd></div>
        <div><dt>Boards</dt><dd>{{ p.boardCount }}</dd></div>
        <div><dt>Members</dt><dd>{{ p.memberCount }}</dd></div>
      </dl>

      <section class="panel">
        <h2>Structure</h2>
        <p class="subtitle">
          <code>getProjectApi().getTree(id, true)</code> — walks the project's full ancestry and
          descendants in one call.
        </p>

        @if (standalone()) {
          <p class="state">This project is standalone — no parent, no children.</p>
          <p class="hint">
            Projects nest into a hierarchy; <code>getTree</code> returns the whole tree from the
            topmost ancestor down. For example:
          </p>
          <ul class="tree example" aria-label="Example project hierarchy">
            <li>
              <div class="node"><span class="name">Enterprise Compliance</span><span class="zb-chip square generic">Portfolio</span></div>
              <ul class="children">
                <li>
                  <div class="node"><span class="name">SOC 2 Program</span><span class="zb-chip square generic">Program</span></div>
                  <ul class="children">
                    <li>
                      <div class="node current"><span class="name">Q1 Evidence Collection</span><span class="zb-chip square generic">Project</span></div>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        } @else if (treeRoot(); as root) {
          <ul class="tree">
            <app-project-tree-node
              [node]="root"
              [currentId]="currentId()"
              (addChild)="createParent.set($event)"
            />
          </ul>
          @if (skippedSubtrees() > 0) {
            <p class="hint">{{ skippedSubtrees() }} sub-tree(s) not shown — the server pruned them.</p>
          }
        }
      </section>

      <section class="panel">
        <h2>Tasks <span class="count">({{ tasks().length }}{{ tasks().length === TASK_PREVIEW ? '+' : '' }})</span></h2>
        @if (tasks().length === 0) {
          <p class="state">No tasks.</p>
        } @else {
          <ul class="tasks">
            @for (t of tasks(); track t.id) {
              <li>
                <code>{{ t.code }}</code>
                <span class="task-name">{{ t.name }}</span>
                <span class="zb-chip square task-status" [ngClass]="t.status">{{ t.status | snakeToSpaces: 'everyFirst' }}</span>
              </li>
            }
          </ul>
        }
      </section>

      <section class="panel">
        <h2>Members <span class="count">({{ members().length }})</span></h2>
        @if (memberRoles().length === 0) {
          <p class="state">No members.</p>
        } @else {
          <ul class="members">
            @for (roles of memberRoles(); track $index) {
              <li>
                <mat-icon>person</mat-icon>
                <span class="roles">{{ roles }}</span>
              </li>
            }
          </ul>
        }
      </section>

      <app-drawer [open]="editOpen()" title="Edit project" (close)="editOpen.set(false)">
        @if (editOpen()) {
          <app-edit-project-form [project]="p" />
        }
      </app-drawer>

      <!-- Sub-project create, opened from any node's "+" — a code-reveal demo like every other
           write in this app: it builds the real NewProject (with parentId) and never posts. -->
      <app-drawer
        [open]="!!createParent()"
        title="Create sub-project"
        (close)="createParent.set(null)"
      >
        @if (createParent(); as parent) {
          <p class="hint">Creating under <strong>{{ parent.name }}</strong></p>
          <app-create-project-form [parentId]="parent.id" />
        }
      </app-drawer>
    }
  `,
  styles: `
    :host { display: block; }
    .back {
      display: inline-flex; align-items: center; gap: 4px;
      color: var(--zb-secondary-text); text-decoration: none;
      font-size: var(--zb-font-size-sm); margin-bottom: var(--zb-spacing-md);
    }
    .back:hover { color: var(--zb-text); }
    .back mat-icon { font-size: 18px; width: 18px; height: 18px; }
    .head { display: flex; align-items: center; justify-content: space-between; gap: var(--zb-spacing-md); }
    .title { display: flex; align-items: center; gap: var(--zb-spacing-sm); flex-wrap: wrap; }
    .title h1 { margin: 0; font-size: 26px; }
    .code { color: var(--zb-primary); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
    .desc { margin: var(--zb-spacing-sm) 0 var(--zb-spacing-md); }
    .meta { display: flex; flex-wrap: wrap; gap: var(--zb-spacing-lg); margin: 0 0 var(--zb-spacing-lg); }
    .meta dt { color: var(--zb-secondary-text); font-size: var(--zb-font-size-xs, 12px); margin: 0; }
    .meta dd { margin: 2px 0 0; color: var(--zb-text); }
    .panel { border: 1px solid var(--zb-divider); border-radius: 8px; padding: var(--zb-spacing-md); margin-bottom: var(--zb-spacing-md); }
    .panel h2 { margin: 0 0 var(--zb-spacing-sm); font-size: 18px; }
    .count { color: var(--zb-secondary-text); font-weight: 400; font-size: var(--zb-font-size-sm); }
    ul { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: var(--zb-spacing-xs); }
    .tasks li, .members li { display: flex; align-items: center; gap: var(--zb-spacing-sm); }
    .subtitle { margin: 0 0 var(--zb-spacing-sm); color: var(--zb-secondary-text); font-size: var(--zb-font-size-sm); }
    .hint { margin: var(--zb-spacing-sm) 0 0; color: var(--zb-secondary-text); font-size: var(--zb-font-size-sm); }
    /* Tree rows come from app-project-tree-node (own styles); these cover the inline
       standalone EXAMPLE, which is static markup rather than real nodes. */
    .tree { gap: 0; }
    .tree li { display: block; }
    .example .node { display: flex; align-items: center; gap: var(--zb-spacing-sm); padding: 4px 0; }
    .example .name { color: var(--zb-primary); }
    .example .node.current .name { color: var(--zb-text); font-weight: 600; }
    .example .children {
      list-style: none; margin: 0 0 0 6px; padding: 0 0 0 var(--zb-spacing-md);
      border-left: 1px solid var(--zb-divider);
    }
    .example { opacity: 0.75; }
    .task-name { flex: 1; }
    .members mat-icon { color: var(--zb-secondary-text); font-size: 18px; width: 18px; height: 18px; }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--zb-primary); }
    .state { color: var(--zb-secondary-text); }
    .state.error { color: var(--zb-color-error); }
    .btn-stroked {
      height: 38px; padding: 0 var(--zb-spacing-md);
      border: 1px solid var(--zb-primary); border-radius: 6px;
      background: transparent; color: var(--zb-primary);
      font-size: var(--zb-font-size-md); cursor: pointer;
    }
    .btn-stroked:hover { background: var(--zb-table-row-hover); }
  `,
})
export class ProjectDetail {
  protected readonly TASK_PREVIEW = TASK_PREVIEW;
  protected readonly editOpen = signal(false);
  /** Non-null while the sub-project drawer is open; carries the node the "+" was clicked on. */
  protected readonly createParent = signal<CreateParent | null>(null);

  /** The four drill-down reads as one auto-cancelling resource (see {@link detailResource}). */
  private readonly detail = detailResource(
    async ({ api, id }) => {
      const projectApi = api.portalClient.getProjectApi();
      const uuid = api.toUUID(id);
      const [project, members, taskResults, tree] = await Promise.all([
        projectApi.get(uuid),
        projectApi.listMembers(uuid),
        projectApi.searchTasks(uuid, {} as SearchTaskBody, 1, TASK_PREVIEW),
        projectApi.getTree(uuid, true),
      ]);
      return { project, members, tasks: taskResults.items, tree };
    },
    { missingId: 'No project id.', loadFailed: 'Could not load this project.' },
  );

  protected readonly loading = this.detail.loading;
  protected readonly error = this.detail.error;
  protected readonly project = computed(() => this.detail.value()?.project ?? null);
  protected readonly members = computed(() => this.detail.value()?.members ?? []);
  protected readonly tasks = computed(() => this.detail.value()?.tasks ?? []);

  /** The whole hierarchy `getTree` returned — root is the topmost ancestor, not this project. */
  protected readonly tree = computed(() => this.detail.value()?.tree ?? null);
  protected readonly treeRoot = computed(() => this.tree()?.root ?? null);
  protected readonly currentId = computed(() => this.tree()?.requestedProjectId?.toString() ?? '');
  /** Sub-trees the server pruned from the response — surfaced so the count isn't silently wrong. */
  protected readonly skippedSubtrees = computed(() => this.tree()?.skippedSubtreeCount ?? 0);

  /**
   * No parent and no children: the tree is just this project, so there is no hierarchy to show.
   * The template then renders an illustrative example instead of an empty panel — the teaching
   * point is what `getTree` returns, which an empty list would fail to convey.
   */
  protected readonly standalone = computed(() => {
    const root = this.treeRoot();
    return !!root && root.id.toString() === this.currentId() && !root.hasChildren;
  });

  /** Per-member role labels, precomputed — the members section renders these directly. */
  protected readonly memberRoles = computed(() =>
    this.members().map((m) => {
      const names = (m.roles ?? []).map((r) => r.name).filter(Boolean);
      return names.length ? names.join(', ') : 'Member';
    }),
  );
}

// package/zerobias/example-nextjs-v2/src/app/projects/detail/ProjectDetail.tsx
"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import type {
  ProjectExtended,
  ProjectMemberExtended,
  ProjectTree,
  ProjectTreeNode,
  TaskExtended,
} from "@zerobias-com/portal-sdk";
import type { UUID } from "@zerobias-org/types-core-js";
import { useSession } from "@/context/session-context";
import { toUserMessage } from "@/lib/errors";
import { Spinner } from "@/components/Spinner";
import { MarkdownViewer } from "@/components/MarkdownViewer";
import { CreateProjectDrawer } from "@/components/CreateProjectDrawer";
import { EditProjectDrawer } from "@/components/EditProjectDrawer";
import { CreateBoardDrawer } from "@/components/CreateBoardDrawer";

type CreateParent = { id: UUID; name: string };

const TASK_PREVIEW = 10;

/**
 * Project detail — the containment chain made concrete. All three reads are on the portal client
 * (the read side of the split), same project id:
 *
 *   portalClient.getProjectApi().get(id)                       -> the project + its counts
 *   portalClient.getProjectApi().listMembers(id)               -> who's on it (users/groups/service accounts)
 *   portalClient.getProjectApi().searchTasks(id, body, page…)  -> the project's tasks, scoped by the project
 *
 * `searchTasks` is the chain payoff: the SAME TaskExtended rows the /tasks demo lists, but scoped
 * to one project — each links straight into the existing task detail. Boards sit between project
 * and task (`boardCount`); a boards demo will surface that middle layer.
 */
export function ProjectDetail() {
  const { api } = useSession();
  // Query-param route (`/projects/detail?id=…`) for the same reason as task detail: static export
  // can't prerender a runtime id as a path. See tasks/detail/TaskDetail.tsx.
  const id = useSearchParams().get("id");

  // Data is tagged with the id it belongs to, so `loading` is DERIVED (stale when loadedId !== id)
  // and every setState stays inside async callbacks (no synchronous setState in the effect).
  const [data, setData] = useState<{
    id: string;
    project: ProjectExtended;
    members: ProjectMemberExtended[];
    tasks: TaskExtended[];
    tree: ProjectTree;
  } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [createParent, setCreateParent] = useState<CreateParent | null>(null);
  const [editing, setEditing] = useState(false);
  const [createBoardOpen, setCreateBoardOpen] = useState(false);

  useEffect(() => {
    if (!api || !id) return;
    let cancelled = false;
    const toUuid = api.toUUID(id);

    Promise.all([
      api.portalClient.getProjectApi().get(toUuid),
      api.portalClient.getProjectApi().listMembers(toUuid),
      // Empty search body = all of the project's tasks, first page.
      api.portalClient.getProjectApi().searchTasks(toUuid, {} as never, 1, TASK_PREVIEW),
      // The whole hierarchy this project sits in — ancestry down through descendants.
      api.portalClient.getProjectApi().getTree(toUuid, true),
    ])
      .then(([project, members, tasks, tree]) => {
        if (cancelled) return;
        setData({ id, project, members, tasks: tasks.items, tree });
        setError(null);
      })
      .catch((err) => {
        if (cancelled) return;
        console.error("Project detail load failed", err);
        setError(toUserMessage(err));
      });

    return () => {
      cancelled = true;
    };
  }, [api, id]);

  const loading = !error && data?.id !== id;

  if (loading) {
    return (
      <p className="state loading-line">
        <Spinner diameter={18} /> Loading project…
      </p>
    );
  }

  if (error) {
    return (
      <div>
        <p className="state error" role="alert">
          Error: {error}
        </p>
        <Link href="/projects">← Back to projects</Link>
      </div>
    );
  }

  if (!data) return null;
  const { project, members, tasks, tree } = data;
  const currentId = tree.requestedProjectId.toString();
  const standalone = tree.root.id.toString() === currentId && !tree.root.hasChildren;

  return (
    <div className="project-detail">
      <Link href="/projects" className="project-detail-back">
        ← Projects
      </Link>

      <div className="project-detail-head">
        <div className="project-detail-head-main">
          <div>
            {project.code && <span className="project-detail-code">{project.code}</span>}
            <h1>{project.name}</h1>
          </div>
          <span className="chip neutral">{String(project.status)}</span>
        </div>
        <div className="project-detail-head-actions">
          <button type="button" className="btn-stroked" onClick={() => setEditing(true)}>
            Edit
          </button>
          <button
            type="button"
            className="btn-stroked"
            onClick={() => setCreateBoardOpen(true)}
          >
            + Create Board
          </button>
          <button
            type="button"
            className="btn-stroked"
            onClick={() => setCreateParent({ id: project.id, name: project.name })}
          >
            + Create Sub-Project
          </button>
        </div>
      </div>

      <EditProjectDrawer project={project} open={editing} onClose={() => setEditing(false)} />

      <CreateBoardDrawer
        open={createBoardOpen}
        onClose={() => setCreateBoardOpen(false)}
        project={{ id: project.id, name: project.name }}
      />

      <CreateProjectDrawer
        open={!!createParent}
        onClose={() => setCreateParent(null)}
        parent={createParent ?? undefined}
      />

      {project.description && (
        <div className="project-detail-desc">
          <MarkdownViewer content={project.description} />
        </div>
      )}

      <dl className="project-detail-meta">
        <div>
          <dt>Type</dt>
          <dd>{project.projectType?.name ?? project.type}</dd>
        </div>
        <div>
          <dt>Visibility</dt>
          <dd>{String(project.visibility)}</dd>
        </div>
        <div>
          <dt>Owner</dt>
          <dd>{project.owner?.name ?? "—"}</dd>
        </div>
        <div>
          <dt>Boards</dt>
          <dd>{project.boardCount ?? 0}</dd>
        </div>
      </dl>

      <section className="project-detail-section">
        <h2>Structure</h2>
        <p className="subtitle">
          <code>getProjectApi().getTree(id, true)</code> — walks the project&apos;s full ancestry
          and descendants in one call.
        </p>
        {standalone ? (
          <div className="project-tree-standalone">
            <p className="state">This project is standalone — no parent, no children.</p>
            <p className="project-detail-hint">
              Projects nest into a hierarchy; <code>getTree</code> returns the whole tree from the
              topmost ancestor down. For example:
            </p>
            <ul className="project-tree project-tree-example" aria-label="Example project hierarchy">
              <li>
                <div className="project-tree-node">
                  <span className="project-tree-name">Enterprise Compliance</span>
                  <span className="project-tree-type">Portfolio</span>
                </div>
                <ul className="project-tree-children">
                  <li>
                    <div className="project-tree-node">
                      <span className="project-tree-name">SOC 2 Program</span>
                      <span className="project-tree-type">Program</span>
                    </div>
                    <ul className="project-tree-children">
                      <li>
                        <div className="project-tree-node current">
                          <span className="project-tree-name">Q1 Evidence Collection</span>
                          <span className="project-tree-type">Project</span>
                        </div>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        ) : (
          <ul className="project-tree">
            <TreeNode node={tree.root} currentId={currentId} onAddChild={setCreateParent} />
          </ul>
        )}
      </section>

      <section className="project-detail-section">
        <h2>
          Tasks <span className="count">{tasks.length}</span>
        </h2>
        <p className="subtitle">
          <code>getProjectApi().searchTasks(id, body, page, size)</code> — the project&apos;s own
          tasks.
        </p>
        {tasks.length === 0 ? (
          <p className="state">No tasks in this project.</p>
        ) : (
          <ul className="project-detail-tasks">
            {tasks.map((t) => (
              <li key={t.id.toString()}>
                <Link href={`/tasks/detail?id=${t.id}`}>
                  <span className="project-detail-code">{t.code}</span>
                  {t.name}
                </Link>
                <span className="chip neutral">{t.status}</span>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section className="project-detail-section">
        <h2>
          Members <span className="count">{members.length}</span>
        </h2>
        <p className="subtitle">
          <code>getProjectApi().listMembers(id)</code>
        </p>
        {members.length === 0 ? (
          <p className="state">No members.</p>
        ) : (
          <ul className="project-detail-members">
            {members.map((m, i) => (
              <li key={i}>
                <strong>{memberLabel(m.member)}</strong>
                <span className="project-detail-roles">
                  {m.roles?.map((r) => r.name).join(", ") || "—"}
                </span>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

// A project member is a user, group, or service account (a union). All carry a display name;
// fall back to email/id for the odd shape rather than rendering "[object Object]".
function memberLabel(member: unknown): string {
  const m = member as { name?: string; email?: string; id?: string };
  return m.name ?? m.email ?? m.id ?? "Unknown";
}

/**
 * Renders a ProjectTree node and its descendants. The node matching `currentId` (the project being
 * viewed) is highlighted and not linked; every other node links to its own detail, so the tree
 * doubles as navigation up the ancestry and down the descendants.
 */
function TreeNode({
  node,
  currentId,
  onAddChild,
}: {
  node: ProjectTreeNode;
  currentId: string;
  onAddChild: (parent: CreateParent) => void;
}) {
  const isCurrent = node.id.toString() === currentId;
  const children = node.children ?? [];
  return (
    <li>
      <div className={`project-tree-node${isCurrent ? " current" : ""}`}>
        {isCurrent ? (
          <span className="project-tree-name">{node.name}</span>
        ) : (
          <Link href={`/projects/detail?id=${node.id}`} className="project-tree-name">
            {node.name}
          </Link>
        )}
        {node.projectType?.name && (
          <span className="project-tree-type">{node.projectType.name}</span>
        )}
        {typeof node.memberCount === "number" && (
          <span className="project-tree-count">{node.memberCount} members</span>
        )}
        <button
          type="button"
          className="project-tree-add"
          aria-label={`Create sub-project of ${node.name}`}
          title={`Create sub-project of ${node.name}`}
          onClick={() => onAddChild({ id: node.id, name: node.name })}
        >
          <span className="material-symbols-outlined" aria-hidden>
            add
          </span>
        </button>
      </div>
      {children.length > 0 && (
        <ul className="project-tree-children">
          {children.map((child) => (
            <TreeNode
              key={child.id.toString()}
              node={child}
              currentId={currentId}
              onAddChild={onAddChild}
            />
          ))}
        </ul>
      )}
    </li>
  );
}
